### ISSUE TITLE
A small typo

### ISSUE THREAD

**Issue by AlexanderSlav** [rvandeghen/SST#1]
Thanks a lot for sharing source code, guys. This is a great research !

There is a small typo, that confuse a liitle bit. In the **Generating the pseudo-labels** section in README should be `label.py` instead of `train.py`
```
PORT=$(( $RANDOM % 50 + 10000 ))
torchrun --nproc_per_node=4 --master_addr 127.0.0.1 --master_port $PORT src/label.py \
         --data-path $dataset \
         --split-unlabeled $split_unlabeled \
         --split-labeled $split_labeled \
         --checkpoint $model \
         --output $output \
         --workers 10
```

**Comment by rvandeghen** [comment]
@AlexanderSlav Thanks for the comment, happy to hear it !

I will change it.
